In [1]:
import numpy as np

In [2]:
# Q1
# Write a program to count the number of vowels and consonants present in an input string
def no_of_vowels_and_consonants(input_string):
    vowels = ['a', 'e', 'i', 'o', 'u'] #list of vowels
    num_vowels = 0  # no of vowels
    num_consonants = 0  # no of consonants

    for char in input_string: # to iterate through every character in the string
        if char.isalpha(): #to check if its a alphabet
            if char.lower() in vowels:
                num_vowels += 1  # cant perform post and pre increment in python
            else:
                num_consonants += 1
                
    return num_vowels, num_consonants

def main():
    print("Q1.")
    input_string = input('Enter a string: ')
    num_vowels, num_consonants = no_of_vowels_and_consonants(input_string)
    print(f"Count of Vowels = {num_vowels} and of Consonants = {num_consonants}")        

if __name__ == "__main__":
    main()


Q1.


Enter a string:  Hello, this is Sneha!


Count of Vowels = 6 and of Consonants = 10


In [3]:
# Q2
# Write a program that accepts two matrices A and B as input and returns their product AB. 
# Check if A & B are multipliable; if not, return error message
def input_matrix():
    rows = int(input('Enter no. of rows: '))
    cols = int(input('Enter no. of columns: '))

    mat = []

    for row in range(rows):
        temp_row = []
        for col in range(cols):
            temp_row.append(int(input(f'Enter matrix[{row+1}][{col+1}] = ')))
        mat.append(temp_row)
    return np.array(mat)

def multiply_matrix(mat_a, mat_b):
    r1, c1 = mat_a.shape
    r2, c2 = mat_b.shape
    if c1 != r2:
        return None
    else:
        return np.dot(mat_a, mat_b)

def main():
    print("\nQ2.")
    mat_a = input_matrix()
    mat_b = input_matrix()
    mat_c = multiply_matrix(mat_a, mat_b)
    if mat_c is None:
        print('The two matrices can\'t be multiplied')
    else:
        print(f'{mat_c}')        

if __name__ == "__main__":
    main()



Q2.


Enter no. of rows:  2
Enter no. of columns:  1
Enter matrix[1][1] =  1
Enter matrix[2][1] =  2
Enter no. of rows:  1
Enter no. of columns:  3
Enter matrix[1][1] =  1
Enter matrix[1][2] =  1
Enter matrix[1][3] =  1


[[1 1 1]
 [2 2 2]]


In [4]:
# Q3
# Write a program to find the number of common elements between two lists. The lists contain integers.
def common_elements_between_two_lists(list1, list2):
    return len(list(np.intersect1d(list1, list2)))

def read_list_elements():
    try:
        temp_list = []
        while True:
            temp_list.append(int(input()))
    # if the input is not a integer
    except:
        return temp_list

def main():
    print("\nQ3.")
    print("Enter element for list 1 (Enter a non integer to stop): ")
    l1 = read_list_elements()
    print("Enter element for list 2: ")
    l2 = read_list_elements()
    print(f"No. of common elements between the 2 lists = {common_elements_between_two_lists(l1, l2)}")
      
if __name__ == "__main__":
    main()


Q3.
Enter element for list 1 (Enter a non integer to stop): 


 1
 2
 3
 4
 5
 


Enter element for list 2: 


 2
 4
 


No. of common elements between the 2 lists = 2


In [5]:
# Write a program that accepts a matrix as input and returns its transpose.
def transpose_of_matrix(mat):
    return np.transpose(mat)

def main():
    print("\nQ4.")
    mat = input_matrix()
    print(f"The original matrix is = ")
    print(mat)
    print(f"Transpose of the matrix is = ")
    print(transpose_of_matrix(mat))        

if __name__ == "__main__":
    main()


Q4.


Enter no. of rows:  2
Enter no. of columns:  3
Enter matrix[1][1] =  1
Enter matrix[1][2] =  2
Enter matrix[1][3] =  3
Enter matrix[2][1] =  4
Enter matrix[2][2] =  5
Enter matrix[2][3] =  6


The original matrix is = 
[[1 2 3]
 [4 5 6]]
Transpose of the matrix is = 
[[1 4]
 [2 5]
 [3 6]]
