In [9]:
import pandas as pd
import numpy as np
!pip install pandas numpy openpyxl

Defaulting to user installation because normal site-packages is not writeable


In [79]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [12]:
df = pd.read_excel('Lab Session Data.xlsx')

In [13]:
print(df.head())

  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)  \
0      C_1           20             6                 2           386   
1      C_2           16             3                 6           289   
2      C_3           27             6                 2           393   
3      C_4           19             1                 2           110   
4      C_5           24             4                 2           280   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  \
0         NaN         NaN         NaN         NaN         NaN  ...   
1         NaN         NaN         NaN         NaN         NaN  ...   
2         NaN         NaN         NaN         NaN         NaN  ...   
3         NaN         NaN         NaN         NaN         NaN  ...   
4         NaN         NaN         NaN         NaN         NaN  ...   

   Unnamed: 12  Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  \
0          NaN          NaN          NaN          NaN          NaN   


In [21]:
columns_to_drop = [f'Unnamed: {i}' for i in range(5, 19)]

# Drop the specified columns
df = df.drop(columns=columns_to_drop, errors='ignore')

columns_to_drop = ['Candy','Mango','Milk']

# Drop the specified columns
df = df.drop(columns=columns_to_drop, errors='ignore')

In [22]:
df

Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [23]:
df.columns.values.tolist()

['Customer', 'Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)', 'Payment (Rs)']

In [29]:
A = df[['Candies (#)', 'Mangoes (Kg)', 'Milk Packets (#)']].to_numpy(dtype=np.int32)

In [38]:
C = df[['Payment (Rs)']].to_numpy(dtype=np.int32)

In [50]:
print("A = ",A)
print("C = ",C)

A =  [[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
C =  [[386]
 [289]
 [393]
 [110]
 [280]
 [167]
 [271]
 [274]
 [148]
 [198]]


In [56]:
# What is the dimensionality of the vector space for this data?
def dimensionality(A):
    return A.shape[1]

In [57]:
# How many vectors exist in this vector space?
def no_of_vectors(A):
    return A.shape[0]

In [58]:
# What is the rank of Matrix A?
def rank(A):
    return np.linalg.matrix_rank(A)

In [59]:
# Using Pseudo-Inverse find the cost of each product available for sale. 
def Pseudo_Inverse(A):
    return np.linalg.pinv(A)

In [64]:
print(f"Dimensionality of the vector space is: {dimensionality(A)}")
print(f"\nNumber of vectors is: {no_of_vectors(A)}")
print(f"\nRank of Matrix A: {rank(A)}")
print("\nCost of each product:")
print(Pseudo_Inverse(A))

Dimensionality of the vector space is: 3

Number of vectors is: 10

Rank of Matrix A: 3

Cost of each product:
[[-0.01008596 -0.03124505  0.01013951  0.0290728   0.0182907   0.01161794
  -0.00771348  0.00095458  0.01743623 -0.00542016]
 [ 0.09059668  0.07263726  0.03172933 -0.09071908 -0.01893196 -0.06926996
   0.05675464  0.03152577 -0.07641966  0.00357352]
 [ 0.00299878  0.15874243 -0.05795468 -0.06609024 -0.06295043  0.03348017
   0.01541831 -0.01070461  0.00029003  0.05938755]]


In [67]:
# Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products available with the vendor.
def predicting_the_cost(A):
    return A_pseudo_inv @ C         # "@" to multiply matrices

print("Predicting the cost of the products available with the vendor:\n", predicting_the_cost(A))

Predicting the cost of the products available with the vendor:
 [[ 1.]
 [55.]
 [18.]]


In [80]:
# A3. Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others 
# as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on 
# purchase behavior
def compute_labels(C):
   
    return np.where(C > 200, 'RICH', 'POOR').flatten()

def main():
    y = compute_labels(C)
    X = A
   
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
      
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
      
    y_pred = model.predict(X_test)
      
    print("Classification Report:")
    print(classification_report(y_test, y_pred, zero_division=0))
   
    print("Accuracy Score:")
    print(accuracy_score(y_test, y_pred))

if __name__ == "__main__":
    main()

Classification Report:
              precision    recall  f1-score   support

        POOR       1.00      1.00      1.00         1
        RICH       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

Accuracy Score:
1.0
