In [2]:
import numpy as np

1. A program to count the number of vowels and consonants present in an input string

In [4]:
def no_of_vowels_and_consonants(input_string):
    vowels = ['a', 'e', 'i', 'o', 'u']  # declaring a list of vowels
    num_vowels = 0  # to store no of vowels
    num_consonants = 0  # to store no of consonants

    for char in input_string: # to iterate through every character in the string
        if char.isalpha(): # checks if the character is an alphabet
            if char.lower() in vowels: # Check if the alphabet is a vowel (case insensitive)
                num_vowels += 1  # Note: we cant perform post and pre increment in python
            else:
                num_consonants += 1
                
    return num_vowels, num_consonants # return the counts of vowels and consonants

def main():
    input_string = input('Enter a string: ') # get the input string from user
    num_vowels, num_consonants = no_of_vowels_and_consonants(input_string)
    print(f"Number of Vowels = {num_vowels} and that of Consonants = {num_consonants}")        

if __name__ == "__main__":
    main()


Enter a string:  Hello, this is Sneha!


Number of Vowels = 6 and that of Consonants = 10


2. A program that accepts two matrices A and B as input and returns their product AB. 

In [9]:
def input_matrix():
    # taking number of rows and columns as input from user
    rows = int(input('Enter no. of rows: '))
    cols = int(input('Enter no. of columns: '))

    # initialising a empty list
    mat = []

    for row in range(rows): # iterate through each row
        temp_row = []
        for col in range(cols): # iterate through each column
            # append the input value to the current row
            temp_row.append(int(input(f'Enter matrix[{row+1}][{col+1}] = '))) 
        mat.append(temp_row) # Append the current row to the matrix
    return np.array(mat)  # convert the list to a numpy array and return

def multiply_matrix(mat_a, mat_b):
    return np.dot(mat_a, mat_b) # perform matrix multiplication and return the result

def main():
    print('For matrix A')
    mat_a = input_matrix() # input the first matrix
    print('\nFor matrix B')
    mat_b = input_matrix() # input the second matrix

    r1, c1 = mat_a.shape # get the number of rows and columns of matrix A
    r2, c2 = mat_b.shape # get the number of rows and columns of matrix B
    if c1 != r2: # check the condition to verify if the 2 matrices can be multiplied
        print('The two matrices can\'t be multiplied')
        
    mat_c = multiply_matrix(mat_a, mat_b) # store the result in variable mat_c
    print(f'\nA.B = \n{mat_c}')        

if __name__ == "__main__":
    main()

For matrix A


Enter no. of rows:  3
Enter no. of columns:  3
Enter matrix[1][1] =  1
Enter matrix[1][2] =  1
Enter matrix[1][3] =  1
Enter matrix[2][1] =  1
Enter matrix[2][2] =  1
Enter matrix[2][3] =  1
Enter matrix[3][1] =  1
Enter matrix[3][2] =  1
Enter matrix[3][3] =  1



For matrix B


Enter no. of rows:  3
Enter no. of columns:  2
Enter matrix[1][1] =  1
Enter matrix[1][2] =  2
Enter matrix[2][1] =  3
Enter matrix[2][2] =  4
Enter matrix[3][1] =  5
Enter matrix[3][2] =  6



A.B = 
[[ 9 12]
 [ 9 12]
 [ 9 12]]


3. A program to find the number of common elements between two lists. The lists contain integers.

In [4]:
def common_elements_between_two_lists(list1, list2):
    # store the intersection of the 2 list and store the common elements as a new list, and return the length of the new list
    return len(list(np.intersect1d(list1, list2))) 

def read_list_elements():
    try:
        temp_list = [] # declare an empty temporary list to store values
        while True: # keep inserting values in list, until input is not a integer number
            temp_list.append(int(input()))
    # if the input is a non integer stop appending values and return the temporary list
    except:
        return temp_list

def main():
    print("\nQ3.")
    print("Enter element for list 1 (Enter a non integer to stop): ")
    l1 = read_list_elements() # input first list
    print("Enter element for list 2: ")
    l2 = read_list_elements() # input second matrix
    print(f"No. of common elements between the 2 lists = {common_elements_between_two_lists(l1, l2)}")
      
if __name__ == "__main__":
    main()


Q3.
Enter element for list 1 (Enter a non integer to stop): 


 1
 2
 3
 4
 5
 


Enter element for list 2: 


 2
 4
 


No. of common elements between the 2 lists = 2


In [5]:
# Write a program that accepts a matrix as input and returns its transpose.
def transpose_of_matrix(mat):
    return np.transpose(mat) # return the transpose of the matrix

def main():
    print("\nQ4.")
    mat = input_matrix() # input the matrix
    print(f"The original matrix is = ")
    print(mat) # print the original matrix
    print(f"Transpose of the matrix is = ")
    print(transpose_of_matrix(mat))  # print the transpose of the matrix        

if __name__ == "__main__":
    main()


Q4.


Enter no. of rows:  2
Enter no. of columns:  3
Enter matrix[1][1] =  1
Enter matrix[1][2] =  2
Enter matrix[1][3] =  3
Enter matrix[2][1] =  4
Enter matrix[2][2] =  5
Enter matrix[2][3] =  6


The original matrix is = 
[[1 2 3]
 [4 5 6]]
Transpose of the matrix is = 
[[1 4]
 [2 5]
 [3 6]]
